postgres:
  database: !ENV POSTGRES_DB
  user: !ENV POSTGRES_USER
  password: !ENV POSTGRES_PASSWORD
  host: !ENV POSTGRES_HOST
  port: !ENV POSTGRES_PORT
  minsize: 1
  maxsize: 5
jwt:
  secret: !ENV JWT_SECRET
  access_exp: !ENV JWT_ACCESS_EXP
  refresh_exp: !ENV JWT_REFRESH_EXP
  algorithm: !ENV JWT_ALGORITHM
  request_property: jwt_payload
