postgres:
  database: "{{POSTGRES_DB}}"
  user: "{{POSTGRES_USER}}"
  password: "{{POSTGRES_PASSWORD}}"
  host: "{{POSTGRES_HOST}}"
  port: "{{POSTGRES_PORT}}"
  minsize: 1
  maxsize: 5
jwt:
  secret: "{{JWT_SECRET}}"
  access_exp: "{{JWT_ACCESS_EXP}}"
  refresh_exp: "{{JWT_REFRESH_EXP}}"
  algorithm: "{{JWT_ALGORITHM}}"
  request_property: jwt_payload
